import { clonePoint, clonePoints } from "../utils/geometry.js";

export class AppState {
  constructor() {
    this.imageWidth = 0;
    this.imageHeight = 0;
    this.originalImage = null;
    this.detectedTrackPoints = [];
    this.userPoints = [];
    this.smoothPath = [];
    this.optimizedPath = [];
    this.apexPoint = null;
    this.speedProfile = [];
    this.segmentTypes = [];
    this.minSpeed = null;
    this.carIndex = 0;
    this.carSubstep = 0;
    this.autoGeneratedPath = false;
  }

  setImage({ imageData, width, height }) {
    this.imageWidth = width;
    this.imageHeight = height;
    this.originalImage = imageData;
    this.clearAllTrackData();
  }

  clearAllTrackData() {
    this.detectedTrackPoints = [];
    this.userPoints = [];
    this.clearComputedData();
    this.autoGeneratedPath = false;
  }

  clearComputedData() {
    this.smoothPath = [];
    this.optimizedPath = [];
    this.apexPoint = null;
    this.speedProfile = [];
    this.segmentTypes = [];
    this.minSpeed = null;
    this.resetCar();
  }

  clearDetectedTrack() {
    this.detectedTrackPoints = [];
  }

  setDetectedTrack(points) {
    this.detectedTrackPoints = clonePoints(points);
  }

  setUserPoints(points, { autoGenerated = false } = {}) {
    this.userPoints = clonePoints(points);
    this.autoGeneratedPath = autoGenerated;
    this.clearComputedData();
  }

  addUserPoint(point) {
    this.userPoints.push(clonePoint(point));
    this.autoGeneratedPath = false;
    this.clearComputedData();
  }

  removeLastUserPoint() {
    if (!this.userPoints.length) return false;
    this.userPoints.pop();
    this.autoGeneratedPath = false;
    this.clearComputedData();
    return true;
  }

  setGeneratedPaths({ smoothPath, optimizedPath }) {
    this.smoothPath = clonePoints(smoothPath);
    this.optimizedPath = clonePoints(optimizedPath);
    this.resetCar();
  }

  setAnalysis({ speedProfile, segmentTypes, apexPoint, minSpeed }) {
    this.speedProfile = [...speedProfile];
    this.segmentTypes = [...segmentTypes];
    this.apexPoint = apexPoint ? clonePoint(apexPoint) : null;
    this.minSpeed = minSpeed;
  }

  getActivePath() {
    return this.optimizedPath.length > 1 ? this.optimizedPath : this.smoothPath;
  }

  resetCar() {
    this.carIndex = 0;
    this.carSubstep = 0;
  }
}
